### ISSUE TITLE
error while starting TinyCoreLinux11.1-1: Could not create 'hda' disk image: qemu-img returned with 1

### ISSUE THREAD

**Issue by mb720** [GNS3/gns3-registry#550]
Hi and thanks for GNS3!

I downloaded and installed the Tiny Core appliances [with](https://gns3.com/marketplace/appliances/firefox-guest) and [without](https://gns3.com/marketplace/appliances/tiny-core-linux) Firefox.

The appliance with Firefox works fine, but when I try to start the other one, I get this error:

    error while starting TinyCoreLinux11.1-1: Could not create 'hda' disk image: qemu-img returned with 1
    qemu-img: /home/mb/.local/share/GNS3/projects/Test_2/project-files/qemu/308610bf-e689-4697-b223-36d2b24a7a3b/hda_disk.qcow2: Could not open backing file: Could not open '/home/gns3/GNS3/images/QEMU/empty30G.qcow2': No such file or directory
    Could not open backing image.

    Could not create 'hda' disk image: qemu-img returned with 1
    qemu-img: /home/mb/.local/share/GNS3/projects/Test_2/project-files/qemu/308610bf-e689-4697-b223-36d2b24a7a3b/hda_disk.qcow2: Could not open backing file: Could not open '/home/gns3/GNS3/images/QEMU/empty30G.qcow2': No such file or directory
    Could not open backing image.

The path for the backing file doesn't look right to me, since there is no directory at `/home/gns3/` on my machine.

I'm running GNS3 2.2.15 on Arch Linux.

Is there a way to fix this issue?

**Comment by b-ehlers** [comment]
See issue https://github.com/GNS3/gns3-server/issues/1817

The tinycore-linux appliance is in bad shape, I suggest to look for alternatives.

**Comment by ZodiaCKiLl3r** [comment]
I have the exact same error but with a different image

error while starting CiscoIOSvL215.2(4.0.55)E-1: Could not create 'hda' disk image: qemu-img returned with 1
qemu-img: /home/zodiac/GNS3/projects/Test/project-files/qemu/b4567084-b1f6-431c-9427-e1c0dbd8912e/hda_disk.qcow2: Backing file specified without backing format
Detected format of vmdk.
Could not create 'hda' disk image: qemu-img returned with 1
qemu-img: /home/zodiac/GNS3/projects/Test/project-files/qemu/b4567084-b1f6-431c-9427-e1c0dbd8912e/hda_disk.qcow2: Backing file specified without backing format
Detected format of vmdk.

I'm running GNS3 2.2.24 on Arch Linux.

Is there a way to fix this issue?

**Comment by grossmj** [comment]
What version of Qemu do you have?

**Comment by b-ehlers** [comment]
I assume, @ZodiaCKiLl3r uses Qemu v6.1. The warning "backing file without format" of previous versions is now an error, see <https://github.com/qemu/qemu/blob/master/docs/about/removed-features.rst#qemu-img-backing-file-without-format-removed-in-61>.

That affects also https://github.com/GNS3/gns3-gui/issues/3131.

A solution would be to query the image format with `qemu-img info --output=json`, attribute format:

```
$ qemu-img info --output=json GNS3/images/QEMU/vEOS-lab-4.14.5F.vmdk
{
    "virtual-size": 2147483648,
    "filename": "GNS3/images/QEMU/vEOS-lab-4.14.5F.vmdk",
    "cluster-size": 65536,
    "format": "vmdk",
    "actual-size": 422383616,
    .
    .
}
```

**Comment by grossmj** [comment]
> A solution would be to query the image format with qemu-img info --output=json, attribute format.

I was thinking using qemu-img  or detecting the file format by looking for the magic value in the header. qemu-img is a much simpler solution... ;)

**Comment by ZodiaCKiLl3r** [comment]
After querying  the  image format with @b-ehlers given command this is the out put,

qemu-img info --output=json image.qcow2        
{
    "virtual-size": 2147483648,
    "filename": "image.qcow2",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 41160704,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "compression-type": "zlib",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false,
            "extended-l2": false
        }
    },
    "dirty-flag": false
}

what should i do now ? i need help please guide me through, :)

**Comment by grossmj** [comment]
@ZodiaCKiLl3r This is a problem with Qemu >= 6.1.0

This should have been fixed on our 2.2 branch: https://github.com/GNS3/gns3-server/tree/2.2

So you have 3 options:

- Downgrade Qemu
- Manually install the development version from https://github.com/GNS3/gns3-server/tree/2.2
- Wait for us to release GNS3 v2.2.25

**Comment by b-ehlers** [comment]
Actually the fixes for Qemu >= 6.1.0 `will fix only the issue @ZodiaCKiLl3r reported. The initial issue from @mb720 (and @vasiliyaltunin reported in https://github.com/GNS3/gns3-server/issues/1817) is not fixed. Therefore Tiny Core Linux v11.1 is still broken.

**Comment by grossmj** [comment]
@b-ehlers correct, my answer is just for @ZodiaCKiLl3r, the OP issue isn't resolved.

**Comment by Benaattia** [comment]
1- Change Path Of Backing File: /home/gns3/GNS3/images/QEMU/empty30G.qcow2

sudo qemu-img rebase -f qcow2 -u -b /opt/gns3/images/QEMU/empty30G.qcow2 linux-tinycore-11.1.qcow2

More information: [https://blog.programster.org/qemu-img-cheatsheet](url)

2- Upgrade template memory to 256 MB
